on: [push, pull_request]
name: Test usql
jobs:
  test:
    name: Build and Test usqlmcp
    runs-on: ubuntu-24.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: stable
    - name: Install Packages
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y build-essential libicu-dev unixodbc unixodbc-dev
    - name: Checkout code
      uses: actions/checkout@v5
    - name: Unit Tests
      run: |
        go test -v ./...
    - name: Build with all drivers
      run: |
        make build.all
